name: Publish Alfred Workflow

on: # yamllint disable-line rule:truthy
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Create release from tag
    runs-on: ubuntu-20.04
    steps:
      - name: Get bjw-s-bot token
        id: get-app-token
        uses: getsentry/action-github-app-token@v1
        with:
          app_id: ${{ secrets.BJWS_APP_ID }}
          private_key: ${{ secrets.BJWS_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v2
        with:
          token: ${{ steps.get-app-token.outputs.token }}
          fetch-depth: 1

      - name: Build Alfred Workflow
        id: alfred_builder
        uses: mperezi/build-alfred-workflow@v1
        with:
          workflow_dir: src
          exclude_patterns: '*.pyc *__pycache__/*'

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ steps.get-app-token.outputs.token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Alfred Workflow
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ steps.get-app-token.outputs.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.alfred_builder.outputs.workflow_file }}
          asset_name: ${{ steps.alfred_builder.outputs.workflow_file }}
          asset_content_type: application/zip
